/*
 * jCarousel - Riding carousels with jQuery
 *   http://sorgalla.com/jcarousel/
 *
 * Copyright (c) 2006 Jan Sorgalla (http://sorgalla.com)
 * Dual licensed under the MIT (http://www.opensource.org/licenses/mit-license.php)
 * and GPL (http://www.opensource.org/licenses/gpl-license.php) licenses.
 *
 * Built on top of the jQuery library
 *   http://jquery.com
 *
 * Inspired by the "Carousel Component" by Bill Scott
 *   http://billwscott.com/carousel/
 */
(function(B){var A={vertical:!1,rtl:!1,start:1,offset:1,size:null,scroll:3,visible:null,animation:"normal",easing:"swing",auto:0,wrap:null,initCallback:null,setupCallback:null,reloadCallback:null,itemLoadCallback:null,itemFirstInCallback:null,itemFirstOutCallback:null,itemLastInCallback:null,itemLastOutCallback:null,itemVisibleInCallback:null,itemVisibleOutCallback:null,animationStepCallback:null,buttonNextHTML:"<div></div>",buttonPrevHTML:"<div></div>",buttonNextEvent:"click",buttonPrevEvent:"click",buttonNextCallback:null,buttonPrevCallback:null,itemFallbackDimension:null},D=!1;
B(window).bind("load.jcarousel",function(){D=!0;}),B.jcarousel=function(N,M){this.options=B.extend({},A,M||{}),this.locked=!1,this.autoStopped=!1,this.container=null,this.clip=null,this.list=null,this.buttonNext=null,this.buttonPrev=null,this.buttonNextState=null,this.buttonPrevState=null,M&&void 0!==M.rtl||(this.options.rtl="rtl"==(B(N).attr("dir")||B("html").attr("dir")||"").toLowerCase()),this.wh=this.options.vertical?"height":"width",this.lt=this.options.vertical?"top":this.options.rtl?"right":"left";
for(var L="",K=N.className.split(" "),J=0;K.length>J;J++){if(-1!=K[J].indexOf("jcarousel-skin")){B(N).removeClass(K[J]),L=K[J];break;}}"UL"==N.nodeName.toUpperCase()||"OL"==N.nodeName.toUpperCase()?(this.list=B(N),this.clip=this.list.parents(".jcarousel-clip"),this.container=this.list.parents(".jcarousel-container")):(this.container=B(N),this.list=this.container.find("ul,ol").eq(0),this.clip=this.container.find(".jcarousel-clip")),0===this.clip.size()&&(this.clip=this.list.wrap("<div></div>").parent()),0===this.container.size()&&(this.container=this.clip.wrap("<div></div>").parent()),""!==L&&-1==this.container.parent()[0].className.indexOf("jcarousel-skin")&&this.container.wrap('<div class=" '+L+'"></div>'),this.buttonPrev=B(".jcarousel-prev",this.container),0===this.buttonPrev.size()&&null!==this.options.buttonPrevHTML&&(this.buttonPrev=B(this.options.buttonPrevHTML).appendTo(this.container)),this.buttonPrev.addClass(this.className("jcarousel-prev")),this.buttonNext=B(".jcarousel-next",this.container),0===this.buttonNext.size()&&null!==this.options.buttonNextHTML&&(this.buttonNext=B(this.options.buttonNextHTML).appendTo(this.container)),this.buttonNext.addClass(this.className("jcarousel-next")),this.clip.addClass(this.className("jcarousel-clip")).css({position:"relative"}),this.list.addClass(this.className("jcarousel-list")).css({overflow:"hidden",position:"relative",top:0,margin:0,padding:0}).css(this.options.rtl?"right":"left",0),this.container.addClass(this.className("jcarousel-container")).css({position:"relative"}),!this.options.vertical&&this.options.rtl&&this.container.addClass("jcarousel-direction-rtl").attr("dir","rtl");
var I=null!==this.options.visible?Math.ceil(this.clipping()/this.options.visible):null,H=this.list.children("li"),G=this;if(H.size()>0){var F=0,E=this.options.offset;H.each(function(){G.format(this,E++),F+=G.dimension(this,I);}),this.list.css(this.wh,F+100+"px"),M&&void 0!==M.size||(this.options.size=H.size());
}this.container.css("display","block"),this.buttonNext.css("display","block"),this.buttonPrev.css("display","block"),this.funcNext=function(){return G.next(),!1;},this.funcPrev=function(){return G.prev(),!1;},this.funcResize=function(){G.resizeTimer&&clearTimeout(G.resizeTimer),G.resizeTimer=setTimeout(function(){G.reload();
},100);},null!==this.options.initCallback&&this.options.initCallback(this,"init"),!D&&C.isSafari()?(this.buttons(!1,!1),B(window).bind("load.jcarousel",function(){G.setup();})):this.setup();};var C=B.jcarousel;C.fn=C.prototype={jcarousel:"0.2.9"},C.fn.extend=C.extend=B.extend,C.fn.extend({setup:function(){if(this.first=null,this.last=null,this.prevFirst=null,this.prevLast=null,this.animating=!1,this.timer=null,this.resizeTimer=null,this.tail=null,this.inTail=!1,!this.locked){this.list.css(this.lt,this.pos(this.options.offset)+"px");
var E=this.pos(this.options.start,!0);this.prevFirst=this.prevLast=null,this.animate(E,!1),B(window).unbind("resize.jcarousel",this.funcResize).bind("resize.jcarousel",this.funcResize),null!==this.options.setupCallback&&this.options.setupCallback(this);}},reset:function(){this.list.empty(),this.list.css(this.lt,"0px"),this.list.css(this.wh,"10px"),null!==this.options.initCallback&&this.options.initCallback(this,"reset"),this.setup();
},reload:function(){if(null!==this.tail&&this.inTail&&this.list.css(this.lt,C.intval(this.list.css(this.lt))+this.tail),this.tail=null,this.inTail=!1,null!==this.options.reloadCallback&&this.options.reloadCallback(this),null!==this.options.visible){var F=this,E=Math.ceil(this.clipping()/this.options.visible),H=0,G=0;
this.list.children("li").each(function(I){H+=F.dimension(this,E),F.first>I+1&&(G=H);}),this.list.css(this.wh,H+"px"),this.list.css(this.lt,-G+"px");}this.scroll(this.first,!1);},lock:function(){this.locked=!0,this.buttons();},unlock:function(){this.locked=!1,this.buttons();},size:function(E){return void 0!==E&&(this.options.size=E,this.locked||this.buttons()),this.options.size;
},has:function(F,E){void 0!==E&&E||(E=F),null!==this.options.size&&E>this.options.size&&(E=this.options.size);for(var H=F;E>=H;H++){var G=this.get(H);if(!G.length||G.hasClass("jcarousel-item-placeholder")){return !1;}}return !0;},get:function(E){return B(">.jcarousel-item-"+E,this.list);},add:function(M,L){var K=this.get(M),J=0,I=B(L);
if(0===K.length){var H,G=C.intval(M);for(K=this.create(M);;){if(H=this.get(--G),0>=G||H.length){0>=G?this.list.prepend(K):H.after(K);break;}}}else{J=this.dimension(K);}"LI"==I.get(0).nodeName.toUpperCase()?(K.replaceWith(I),K=I):K.empty().append(L),this.format(K.removeClass(this.className("jcarousel-item-placeholder")),M);
var F=null!==this.options.visible?Math.ceil(this.clipping()/this.options.visible):null,E=this.dimension(K,F)-J;return M>0&&this.first>M&&this.list.css(this.lt,C.intval(this.list.css(this.lt))-E+"px"),this.list.css(this.wh,C.intval(this.list.css(this.wh))+E+"px"),K;},remove:function(F){var E=this.get(F);
if(E.length&&!(F>=this.first&&this.last>=F)){var G=this.dimension(E);this.first>F&&this.list.css(this.lt,C.intval(this.list.css(this.lt))+G+"px"),E.remove(),this.list.css(this.wh,C.intval(this.list.css(this.wh))-G+"px");}},next:function(){null===this.tail||this.inTail?this.scroll("both"!=this.options.wrap&&"last"!=this.options.wrap||null===this.options.size||this.last!=this.options.size?this.first+this.options.scroll:1):this.scrollTail(!1);
},prev:function(){null!==this.tail&&this.inTail?this.scrollTail(!0):this.scroll("both"!=this.options.wrap&&"first"!=this.options.wrap||null===this.options.size||1!=this.first?this.first-this.options.scroll:this.options.size);},scrollTail:function(F){if(!this.locked&&!this.animating&&this.tail){this.pauseAuto();
var E=C.intval(this.list.css(this.lt));E=F?E+this.tail:E-this.tail,this.inTail=!F,this.prevFirst=this.first,this.prevLast=this.last,this.animate(E);}},scroll:function(F,E){this.locked||this.animating||(this.pauseAuto(),this.animate(this.pos(F),E));},pos:function(X,W){var V=C.intval(this.list.css(this.lt));
if(this.locked||this.animating){return V;}"circular"!=this.options.wrap&&(X=1>X?1:this.options.size&&X>this.options.size?this.options.size:X);for(var M,U=this.first>X,T="circular"!=this.options.wrap&&1>=this.first?1:this.first,S=U?this.get(T):this.get(this.last),R=U?T:T-1,Q=null,P=0,O=!1,N=0;U?--R>=X:X>++R;
){Q=this.get(R),O=!Q.length,0===Q.length&&(Q=this.create(R).addClass(this.className("jcarousel-item-placeholder")),S[U?"before":"after"](Q),null!==this.first&&"circular"==this.options.wrap&&null!==this.options.size&&(0>=R||R>this.options.size)&&(M=this.get(this.index(R)),M.length&&(Q=this.add(R,M.clone(!0))))),S=Q,N=this.dimension(Q),O&&(P+=N),null!==this.first&&("circular"==this.options.wrap||R>=1&&(null===this.options.size||this.options.size>=R))&&(V=U?V+N:V-N);
}var L=this.clipping(),K=[],J=0,I=0;for(S=this.get(X-1),R=X;++J;){if(Q=this.get(R),O=!Q.length,0===Q.length&&(Q=this.create(R).addClass(this.className("jcarousel-item-placeholder")),0===S.length?this.list.prepend(Q):S[U?"before":"after"](Q),null!==this.first&&"circular"==this.options.wrap&&null!==this.options.size&&(0>=R||R>this.options.size)&&(M=this.get(this.index(R)),M.length&&(Q=this.add(R,M.clone(!0))))),S=Q,N=this.dimension(Q),0===N){throw Error("jCarousel: No width/height set for items. This will cause an infinite loop. Aborting...");
}if("circular"!=this.options.wrap&&null!==this.options.size&&R>this.options.size?K.push(Q):O&&(P+=N),I+=N,I>=L){break;}R++;}for(var H=0;K.length>H;H++){K[H].remove();}P>0&&(this.list.css(this.wh,this.dimension(this.list)+P+"px"),U&&(V-=P,this.list.css(this.lt,C.intval(this.list.css(this.lt))-P+"px")));
var G=X+J-1;if("circular"!=this.options.wrap&&this.options.size&&G>this.options.size&&(G=this.options.size),R>G){for(J=0,R=G,I=0;++J&&(Q=this.get(R--),Q.length)&&(I+=this.dimension(Q),!(I>=L));){}}var F=G-J+1;if("circular"!=this.options.wrap&&1>F&&(F=1),this.inTail&&U&&(V+=this.tail,this.inTail=!1),this.tail=null,"circular"!=this.options.wrap&&G==this.options.size&&G-J+1>=1){var E=C.intval(this.get(G).css(this.options.vertical?"marginBottom":"marginRight"));
I-E>L&&(this.tail=I-L-E);}for(W&&X===this.options.size&&this.tail&&(V-=this.tail,this.inTail=!0);X-->F;){V+=this.dimension(this.get(X));}return this.prevFirst=this.first,this.prevLast=this.last,this.first=F,this.last=G,V;},animate:function(E,J){if(!this.locked&&!this.animating){this.animating=!0;var I=this,H=function(){if(I.animating=!1,0===E&&I.list.css(I.lt,0),!I.autoStopped&&("circular"==I.options.wrap||"both"==I.options.wrap||"last"==I.options.wrap||null===I.options.size||I.last<I.options.size||I.last==I.options.size&&null!==I.tail&&!I.inTail)&&I.startAuto(),I.buttons(),I.notify("onAfterAnimation"),"circular"==I.options.wrap&&null!==I.options.size){for(var K=I.prevFirst;
I.prevLast>=K;K++){null===K||K>=I.first&&I.last>=K||!(1>K||K>I.options.size)||I.remove(K);}}};if(this.notify("onBeforeAnimation"),this.options.animation&&J!==!1){var G=this.options.vertical?{top:E}:this.options.rtl?{right:E}:{left:E},F={duration:this.options.animation,easing:this.options.easing,complete:H};
B.isFunction(this.options.animationStepCallback)&&(F.step=this.options.animationStepCallback),this.list.animate(G,F);}else{this.list.css(this.lt,E+"px"),H();}}},startAuto:function(F){if(void 0!==F&&(this.options.auto=F),0===this.options.auto){return this.stopAuto();}if(null===this.timer){this.autoStopped=!1;
var E=this;this.timer=window.setTimeout(function(){E.next();},1000*this.options.auto);}},stopAuto:function(){this.pauseAuto(),this.autoStopped=!0;},pauseAuto:function(){null!==this.timer&&(window.clearTimeout(this.timer),this.timer=null);},buttons:function(F,E){null==F&&(F=!this.locked&&0!==this.options.size&&(this.options.wrap&&"first"!=this.options.wrap||null===this.options.size||this.last<this.options.size),this.locked||this.options.wrap&&"first"!=this.options.wrap||null===this.options.size||!(this.last>=this.options.size)||(F=null!==this.tail&&!this.inTail)),null==E&&(E=!this.locked&&0!==this.options.size&&(this.options.wrap&&"last"!=this.options.wrap||this.first>1),this.locked||this.options.wrap&&"last"!=this.options.wrap||null===this.options.size||1!=this.first||(E=null!==this.tail&&this.inTail));
var G=this;this.buttonNext.size()>0?(this.buttonNext.unbind(this.options.buttonNextEvent+".jcarousel",this.funcNext),F&&this.buttonNext.bind(this.options.buttonNextEvent+".jcarousel",this.funcNext),this.buttonNext[F?"removeClass":"addClass"](this.className("jcarousel-next-disabled")).attr("disabled",F?!1:!0),null!==this.options.buttonNextCallback&&this.buttonNext.data("jcarouselstate")!=F&&this.buttonNext.each(function(){G.options.buttonNextCallback(G,this,F);
}).data("jcarouselstate",F)):null!==this.options.buttonNextCallback&&this.buttonNextState!=F&&this.options.buttonNextCallback(G,null,F),this.buttonPrev.size()>0?(this.buttonPrev.unbind(this.options.buttonPrevEvent+".jcarousel",this.funcPrev),E&&this.buttonPrev.bind(this.options.buttonPrevEvent+".jcarousel",this.funcPrev),this.buttonPrev[E?"removeClass":"addClass"](this.className("jcarousel-prev-disabled")).attr("disabled",E?!1:!0),null!==this.options.buttonPrevCallback&&this.buttonPrev.data("jcarouselstate")!=E&&this.buttonPrev.each(function(){G.options.buttonPrevCallback(G,this,E);
}).data("jcarouselstate",E)):null!==this.options.buttonPrevCallback&&this.buttonPrevState!=E&&this.options.buttonPrevCallback(G,null,E),this.buttonNextState=F,this.buttonPrevState=E;},notify:function(F){var E=null===this.prevFirst?"init":this.prevFirst<this.first?"next":"prev";this.callback("itemLoadCallback",F,E),this.prevFirst!==this.first&&(this.callback("itemFirstInCallback",F,E,this.first),this.callback("itemFirstOutCallback",F,E,this.prevFirst)),this.prevLast!==this.last&&(this.callback("itemLastInCallback",F,E,this.last),this.callback("itemLastOutCallback",F,E,this.prevLast)),this.callback("itemVisibleInCallback",F,E,this.first,this.last,this.prevFirst,this.prevLast),this.callback("itemVisibleOutCallback",F,E,this.prevFirst,this.prevLast,this.first,this.last);
},callback:function(O,N,M,L,K,J,I){if(null!=this.options[O]&&("object"==typeof this.options[O]||"onAfterAnimation"==N)){var H="object"==typeof this.options[O]?this.options[O][N]:this.options[O];if(B.isFunction(H)){var G=this;if(void 0===L){H(G,M,N);}else{if(void 0===K){this.get(L).each(function(){H(G,this,L,M,N);
});}else{for(var F=function(P){G.get(P).each(function(){H(G,this,P,M,N);});},E=L;K>=E;E++){null===E||E>=J&&I>=E||F(E);}}}}}},create:function(E){return this.format("<li></li>",E);},format:function(E,H){E=B(E);for(var G=E.get(0).className.split(" "),F=0;G.length>F;F++){-1!=G[F].indexOf("jcarousel-")&&E.removeClass(G[F]);
}return E.addClass(this.className("jcarousel-item")).addClass(this.className("jcarousel-item-"+H)).css({"float":this.options.rtl?"right":"left","list-style":"none"}).attr("jcarouselindex",H),E;},className:function(E){return E+" "+E+(this.options.vertical?"-vertical":"-horizontal");},dimension:function(E,H){var G=B(E);
if(null==H){return this.options.vertical?G.innerHeight()+C.intval(G.css("margin-top"))+C.intval(G.css("margin-bottom"))+C.intval(G.css("border-top-width"))+C.intval(G.css("border-bottom-width"))||C.intval(this.options.itemFallbackDimension):G.innerWidth()+C.intval(G.css("margin-left"))+C.intval(G.css("margin-right"))+C.intval(G.css("border-left-width"))+C.intval(G.css("border-right-width"))||C.intval(this.options.itemFallbackDimension);
}var F=this.options.vertical?H-C.intval(G.css("marginTop"))-C.intval(G.css("marginBottom")):H-C.intval(G.css("marginLeft"))-C.intval(G.css("marginRight"));return B(G).css(this.wh,F+"px"),this.dimension(G);},clipping:function(){return this.options.vertical?this.clip[0].offsetHeight-C.intval(this.clip.css("borderTopWidth"))-C.intval(this.clip.css("borderBottomWidth")):this.clip[0].offsetWidth-C.intval(this.clip.css("borderLeftWidth"))-C.intval(this.clip.css("borderRightWidth"));
},index:function(F,E){return null==E&&(E=this.options.size),Math.round(((F-1)/E-Math.floor((F-1)/E))*E)+1;}}),C.extend({defaults:function(E){return B.extend(A,E||{});},intval:function(E){return E=parseInt(E,10),isNaN(E)?0:E;},windowLoaded:function(){D=!0;},isSafari:function(){var F=navigator.userAgent.toLowerCase(),E=/(chrome)[ \/]([\w.]+)/.exec(F)||/(webkit)[ \/]([\w.]+)/.exec(F)||[],G=E[1]||"";
return"webkit"===G;}}),B.fn.jcarousel=function(E){if("string"==typeof E){var G=B(this).data("jcarousel"),F=Array.prototype.slice.call(arguments,1);return G[E].apply(G,F);}return this.each(function(){var H=B(this).data("jcarousel");H?(E&&B.extend(H.options,E),H.reload()):B(this).data("jcarousel",new C(this,E));
});};})(jQuery);