/*
 Copyright Andrew Lyczak.  All rights reserved.  No HTML pages and/or Javascript may be reproduced without prior permission of the author. */
function lnw(a){return parseInt(a.getAttribute("lw"))}function setq(a,c){a.setAttribute("q",c)}function getq(a){return parseInt(a.getAttribute("q"))}function seta(a,c){a.setAttribute("a",c)}function geta(a){return parseInt(a.getAttribute("a"))}var jgc=null;function w66(){if(!jgc)if(window.quiz&&quiz.wzGraphics)jgc=quiz.wzGraphics;else return;var a=jgc.cnv;jgc.cnv=this;jgc.clear();jgc.h95(this.style.color);jgc.jT2(lnw(this));this.drawShape();jgc.paint();jgc.cnv=a}
function tqDrawTri(){var a=lnw(this),c=offh(this)-2,b=offw(this)-2,e=jH(c-a,0),f=jH(b-a,0);(b<=a||c<=a)&&jgc.jT2(jy(a,c-2,b-2));var a=getq(this),c=geta(this),b=0>c?mrnd(f+f*(c/180)):f,d=0<c?mrnd(f-f*(c/180)):f,b=[0,b,d],d=[e,e,0];a&2&&(b=map(b,function(a){return f-a}));2<a&&(d=map(d,function(a){return e-a}));b=map(b,mrnd);d=map(d,mrnd);"N"==this.id.charAt(0)?jgc.uZ3(b,d):jgc.v56(b,d);var g=distance([b[1],d[1]],[b[2],d[2]]),h=distance([b[0],d[0]],[b[2],d[2]]);distance([b[0],d[0]],[b[1],d[1]]);d=Math.asin(e/
h);g=Math.asin(e/g);if(a&2&&b[1]>b[2]||!(a&2)&&b[1]<b[2])g=Math.PI-g;d=mrnd(Z2(d));g=90==c?d:mrnd(Z2(g));b=mrnd(180-d-g,100);if((c=q9("extrainfo"))&&"extraInfoOn"==c.className)b=!isNaN(g)&&d&&g&&b?d+Wl+" "+g+Wl+" "+b+Wl+"<br/>":"",c.innerHTML=b+"<span style='font-family:Courier'>+</span> Make obtuse<br/><span style='font-family:Courier'>-</span> Make acute",osl(c,a&2?this.offsetLeft+(this.offsetWidth>>1)-2:this.offsetLeft+this.offsetWidth+2),ost(c,3>a?this.offsetTop-c.offsetHeight-2:this.offsetTop+
this.offsetHeight+2)}function tqDrawOval(){var a=lnw(this),c=offw(this),b=offh(this);(c<=a||b<=a)&&jgc.jT2(jy(a,b-2,c-2));"P"==this.id.charAt(0)?jgc.uZ4(0,0,jH(c-2,0),jH(b-2,0)):jgc.v57(0,0,jH(c-a-2,0),jH(b-a-2,0))}
function tqDrawLine(){var a=lnw(this),c=offw(this)-2,b=offh(this)-2;if(c<=a&&b<=a)return jgc.mkDiv(0,0,a,a);var e=jH(c-a,0),f=jH(b-a,0),a=getq(this);a&1?jgc.jf0(0,f,e,0):jgc.jf0(0,0,e,f);jgc.paint();var e=J5?jgc.cnv.childNodes:children(jgc.cnv,"DIV"),d=0,g=0,f=e[0],h=e[e.length-1],j=null,c=c+2,b=b+2;1==a?g=b-(parseInt(f.style.top)+parseInt(f.style.height)+2):2==a?(g=b-(parseInt(h.style.top)+parseInt(h.style.height)+2),d=c-(parseInt(h.style.left)+parseInt(h.style.width)+2)):3==a&&(d=c-(parseInt(h.style.left)+
parseInt(h.style.width)+2));d&&g?j=function(a){ost(a,parseInt(a.style.top)+g);osl(a,parseInt(a.style.left)+d)}:d?j=function(a){osl(a,parseInt(a.style.left)+d)}:g&&(j=function(a){ost(a,parseInt(a.style.top)+g)});j&&map(e,j)}
function tqDrawArrow(){var a=lnw(this),c=offw(this)-2,b=offh(this)-2,e=jH(c-a,0),f=jH(b-a,0),b=getq(this),c=jH(distance([0,0],[e,f]),1),d=2*Math.sqrt(a)*Math.log(c)/c,g=(1-d)*e,h=(1-d)*f,j=d*f,d=d*e,i=[0,g,g-j,g+j,e],k=[0,h,h+d,h-d,f];3>b&&(k=map(k,function(a){return f-a}));b&2&&(i=map(i,function(a){return e-a}));b=function(a,b){i[a]=(i[a]+i[b])/2;k[a]=(k[a]+k[b])/2};b(2,1);b(3,1);if(1<a)for(b=2;4>=b;b++)i[b]+=0.5*(a-1)*f/c,k[b]+=0.5*(a-1)*e/c;i=map(i,mrnd);k=map(k,mrnd);jgc.jf0(i[0],k[0],i[1],k[1]);
jgc.uZ3(i.slice(2),k.slice(2))}function tqTblDimensions(a){var c={rows:0,cols:0};if(a&&(a=parseInt(a)))c.rows=a&255,c.cols=a>>8&255;return c}
function tqDrawRect(){var a=lnw(this),c=offh(this)-2,b=offw(this)-2,e=jH(c-a,0),f=jH(b-a,0),d=tqTblDimensions(geta(this)),g=d.rows,d=d.cols;if(b<=a||c<=a||"F"==this.id.charAt(0))return jgc.mkDiv(0,0,jH(b,0),jH(c,0));getq(this)||(jgc.mkDiv(0,0,b,a),jgc.mkDiv(f,0,a,c),jgc.mkDiv(0,e,b,a),jgc.mkDiv(0,0,a,c));for(var h=1;h<g;h++)jgc.mkDiv(0,mrnd(h*e/g)-(a>>1),b,a);for(h=1;h<d;h++)jgc.mkDiv(mrnd(h*f/d)-(a>>1),0,a,c)}
function tqVid(){var a=this.getAttribute("a"),c=this.getAttribute("q")||"ytv",b=offw(this)-1,e=offh(this)-10;this.innerHTML='<div style="width:100%;height:10px;font-size:0px;overflow:hidden;" p="'+this.id+'"></div>'+i96(c+"-"+a+"-"+b+"-"+e,!1)}function tqDrawGraph(){window.graphModule&&graphModule.nJ8(this,jgc)}
function tqSetShape(a){if(a.id){var c=a.id.charAt(0);if("V"==c)a.render=tqVid;else if(aZ1("RFOPGNLWA".split(""),c))switch(a.render=w66,a.onUp=this&&this.aW&&"A"!=c?this.aW:null,c){case "R":case "F":a.drawShape=tqDrawRect;break;case "O":case "P":a.drawShape=tqDrawOval;break;case "G":case "N":a.drawShape=tqDrawTri;break;case "L":a.drawShape=tqDrawLine;break;case "W":a.drawShape=tqDrawArrow;break;case "A":a.drawShape=tqDrawGraph}}}
function Freehand(){this.name="Test";this.group=9;this.re=jX5(/^ZF(.+)$/);this.imagere=fV0;this.qd=this.ca=null;this.Bf8=[];this.jA8=1;this.CORRECT=2;this.INCORRECT=3;this.IDITEM=4;this.Dg9={};this.Jk=this.Bj8=!0;this.VD={};this.vJ9=function(a,c){return this.re.test(a)&&this.re.test(c)?fZP(parseInt(this.re.exec(a)[1]),parseInt(this.re.exec(c)[1])):0};this.w88=null;this.hj1=jX5('(font-size\\:|width\\:|height\\:|top\\:|left\\:|lw\\=)([\\s"]?)(\\-?\\d+)(px|")',"gi");this.jU7=jX5("<input[^>]* type=[\"']?radio['\"]?[^>]*>",
"gi");this.qJ1=function(a){return'<span style="margin-left:2px;margin-right:1px;font-size:6px;">'+(/checked/i.test(a)?"&#9673;":"&#9675;")+"</span>"};this.q82=150;this.vY0=function(a,c){var b=this.qd=a.substr(2),e=q9("scratchcanvas"),f=q9("emptydiv"),d=this.q82,g,h;if(c&&(h=c.firstChild)){e||(e=document.body.appendChild(Gg("DIV")),e.id="scratchcanvas");if(!jgc||jgc.cnv!=e)jgc=new wzGraphics("scratchcanvas");f||(f=document.body.appendChild(Gg("DIV")),f.id="emptydiv");b=b.replace(/<div /i,"<div class='freehand' ");
f.innerHTML="<div style='left:0px;top:0px;position:absolute;text-align:left;'>"+b+"</div>";this.jX0(f.firstChild.firstChild,!0);b=f.innerHTML;g=offh(f);d=Math.min(0.5,d/g);d!=this.w88&&(this.resizef=new Function("s","a","b","c","d","return(a+b+Math[/(top|TOP|left|LEFT)/.test(a)?'round':'ceil'](parseInt(c)*"+(this.w88=d)+")+d);"));b=b.replace(this.hj1,this.resizef);b=b.replace(this.jU7,this.qJ1);e.innerHTML=f.innerHTML="";h.innerHTML=b}};this.describe=function(){return"<div class='thumbpad' style='position:relative;width:227px;height:"+
(this.q82+2)+"px;margin-top:-15px;margin-left:50px;margin-bottom:2px;overflow:hidden;'></div>"};this.uM6=function(){this.n7||(this.n7=1);for(var a=/<img[^<]* a=['"]?(\w+)["']?/gi,c=null,b=null,e=null;this.n7<quiz.testDef.length;this.n7++)if(c=quiz.testDef[this.n7].match(this.re)){for(;b=a.exec(c[1]);)this.VD[b[1]]||(this.VD[b[1]]=e=new Image,e.src=uQ1(b[1]));if(e){this.n7++;break}}};this.Bf=function(a){map(a.getElementsByTagName("A"),getf("target='_blank'"))};this.Cv=function(a){return"V"==a.id.charAt(0)};
this.Dd=function(a){return"X"==a.id.charAt(0)};this.jX0=function(a,c){this.inps=children(a,"INPUT");var b,e=this.iditems=[],f=children(a,"IMG"),d=children(a),g=this.Jw=filter(d,this.Dd),h=0,j="<br/><center><button id='frhok' class='qZ3' type='button' onclick='freehand.v86()'>OK</button></center>";this.roptions=[];this.Mq=[];this.otxt="";map(d,function(a){ocn(a,"fit");tqSetShape(a);a.render&&a.render()});!c&&f.length&&aev(f[f.length-1],"load",function(){i.uM6()});map(f,function(a){var b;if(b=a.getAttribute("a"))a.src=
this.VD[b]=uQ1(b)},this,[]);map(g,this.Bf);map(d,function(a){"IMG"!=a.nodeName&&!this.Cv(a)&&(h=jH(h,offt(a)+offh(a)))},this,[]);d=a.parentNode;h>offh(a)&&osh(a,h);h=offh(a);h>offh(d)&&(osh(d,h),osh(d.parentNode,h));if(!c){quiz.retest||(this.Dg9[this.pd]=[]);var i=this,k=this.Dg9[this.pd],n=function(a){return!quiz.retest||!aZ1(k,a.id)},d=function(a){return!n(a)},q="fJg"+(this.fJz?++this.fJz:this.fJz=1);map(filter(this.inps,d),getf("disabled=true"));map(this.inps=filter(this.inps,n),function(a){a.val=
a.value;a.value="";aev(a,"keyup",i.hjs)});for(var g=filter(g,n),l,m,p,r=0;r<g.length;r++)if(l=g[r],m=geta(l),aZ1([this.CORRECT,this.INCORRECT],m)&&(p=l.getElementsByTagName("INPUT")).length)this.roptions.push(p=p[0]),seta(p,geta(l)),p.name=q,p.id="R"+l.id,n(p)?aev(p,"click",i.hjs):p.checked=!0;else if(m==this.IDITEM)ocn(l,"idq"),this.Mq.push(m=Gg("DIV")),m.id="QM"+l.id,ocn(m,"frhq"),m.innerHTML='<div style="text-align:center;vertical-align:middle;'+(Wd?"":"margin-top:-2px;")+'">?</div>',a.appendChild(m),
osl(m,mrnd(l.offsetLeft+l.offsetWidth/2-offw(m)/2)-1),ost(m,mrnd(l.offsetTop+l.offsetHeight/2-offh(m)/2)),l.style.paddingLeft=l.style.paddingRight="1px",e.push(l);else if(m==this.jA8&&(b=iE7(l)).length>this.otxt.length)this.otxt=b;filter(this.roptions,d).length&&(map(this.roptions,getf("disabled=true")),this.roptions=[]);e.length?(quiz.bbhtm("<div id='fZA'></div>"+j),map(e,function(a){i.iE5(a);aev(a,"mousedown",new Function("e","freehand.o98(q9('"+a.id+"'),e)"))}),this.yJ9()):quiz.bbhtm(j);quiz.hjq(a);
this.inps.length&&n78(this.inps[0].id);f.length||setTimeout("freehand.uM6()",10)}};this.v93=function(a){return(a=zE2(a))&&"INPUT"==a.nodeName&&"text"==a.type.toLowerCase()};this.show=function(a,c){var b=quiz,e=(this.qd=(this.pd=a).substr(2)).replace(/<div /i,"<div id='frh' class='freehand' "),f,d,g=(d=/width\s*:\s*(\d+)px/.exec(e))?d.pop():null,h=(d=/height\s*:\s*(\d+)px/.exec(e))?d.pop():null;b.n70("wzGraphics",g,h);q9("canvas").innerHTML="<div id='fZE'>"+e+"</div>";children(e=q9("frh")).length?
(this.jX0(e,c),aev(document,"selectstart",this.v93)):quiz.Pg();!b.retest&&(f=b.s98().qm)&&map(f,function(a){this.paste(b.qF().appendChild(q9(a.pasted)),q9(a.id))},this,[])};this.DQ0=function(a){this.show(a,!0);var a=filter(this.Jw,function(a){return geta(a)==freehand.CORRECT}),c=filter(this.Jw,function(a){return geta(a)==freehand.INCORRECT});map(a,getf("firstChild.checked=true"));map(c,getf("style.color='#AAAAAA'"));quiz.bbhtm("")};this.qE=function(a){a=bJd(a);quiz.accentSensitive||(a=latin(a));quiz.caseSensitive||
(a=a.toLowerCase());return a};this.v86=function(){function a(a){return a.getAttribute("alt")}function c(a,b){var c=offt(a)-offt(b),e=offl(a)-offl(b);return Math.abs(e)>Math.abs(c)?e:c}quiz.begin();var b,e,f=this.otxt||"",d=this.Mq,g=this.inps,h=0,j,i,k,n;f.length&&(f+=" : ");quiz.retest||(this.Dg9[this.pd]=[]);var q=this.Dg9[this.pd];for(i=0;i<d.length;i++)b=d[i].id.substr(2),(e=d[i].pasted)&&e.id==b?(quiz.kJ6(),q.push(b)):(quiz.i83(iE7(q9(b)),e?iE7(e):"",i),h++);e=g.slice(0);g=1==e.length||1==v97(map(e,
a)).length?f:"";for(b=0;inp=e.shift();){j=a(inp);inp=[inp];if(j)for(i=e.length-1;0<=i;i--)a(e[i])==j&&inp.push(e.splice(i,1).shift());inp.sort(c);i=this.qE(k=map(inp,getf("val")).join("/"));j=this.qE(n=map(inp,getf("value")).join("/"));j==i?(quiz.kJ6(),map(inp,function(a){q.push(a.id)})):(quiz.i83(g+k,n,d.length+b),h++);b++}g=filter(this.roptions,function(a){return geta(a)==freehand.CORRECT});if(g.length&&(g=g[0]))e=this.zJ9(),g==e?(quiz.kJ6(),q.push(g.id)):(g=iE7(q9(g.id.substr(1))),e=e?iE7(q9(e.id.substr(1))):
"",quiz.i83(f+g,e,d.length+b),h++);evd(document,"selectstart",this.v93);sdn(q9("frhok"));map(this.iditems,osbgc,{},["#CCCCCC"]);map(this.iditems,getf("style.cursor='default'"));quiz.s98().qm=map(filter(d,getf("pasted")),function(a){return{id:a.id,pasted:a.pasted.id}});quiz.Pg(h)};this.g45=function(a){return!a.pasted};this.unanswered=function(a){return""==a.value};this.zJ9=function(){var a=filter(this.roptions,getf("checked"));return a.length?a[0]:!1};this.hjv=function(a){return!!a.pasted};this.hjt=
function(){quiz.s98().qm=map(filter(this.Mq,this.hjv),function(a){return{id:a.id,pasted:a.pasted.id}})};this.unfinished=function(){var a=filter(this.Mq,this.g45),c=filter(this.inps,this.unanswered);c.length&&c[0].focus();return a.length||c.length||this.roptions.length&&!this.zJ9()};this.r89=function(a){var c,b=zE2(a);if(aZ1(c=freehand.roptions,b))map(c,getf("checked=false")),b.checked=!0;else if(13==s97(a))return freehand.unfinished()||freehand.v86(),!0};this.hjs=function(a){quiz.begin();quiz.zH7||
quiz.remember(!1);freehand.r89(a)};this.Qb=Qb;this.Pk=Pk;this.yJ9=function(){var a=q9("fZA"),c,b=children(a,"SPAN");b.sort(function(a,b){return fZP(b.firstChild.offsetHeight,a.firstChild.offsetHeight)||fZP(g47(a),g47(b))});map(b,function(b){a.removeChild(b)});map(b,function(b){(c=a.lastChild)&&c.offsetLeft+parseInt(c.style.marginRight)+parseInt(b.style.marginRight)>a.offsetWidth&&a.appendChild(Gg("BR"));a.appendChild(b)})};this.iE5=function(a){osl(a,0);ost(a,0);var c=q9("frh").style.fontSize,b=q9("fZA").appendChild(Gg("SPAN"));
b.style.position="relative";b.style.marginRight=a.offsetWidth+4+"px";J5?(osh(b,a.offsetHeight+4),b.style.fontSize=c,b.id="WR"+a.id):b.innerHTML="<span style='position:relative;white-space:nowrap;font-size:"+a.offsetHeight+"px' ><span id='WR"+a.id+"' style='font-size:"+c+"'></span>&nbsp;</span>";q9("WR"+a.id).appendChild(a)};this.uG3=function(a){osl(a,0);ost(a,0);var c=q9("WR"+a.id);c&&c.appendChild(a)};this.iE2=function(a){var c=q9("frh"),b=offl(a)+(offw(a)>>1),a=offt(a)+(offh(a)>>1);return 0<b&&
0<a&&b<c.offsetWidth&&a<c.offsetHeight};this.paste=function(a,c){c.pasted&&c.pasted!=a&&this.uG3(c.pasted);c.pasted=a;osl(a,offl(c)+2+(offw(c)-offw(a)>>1));ost(a,offt(c)+(offh(c)>>1)-(offh(a)>>1))};this.Bf2=function(a){for(var c,b=this.Mq,e=function(a){return[offl(a)+(offw(a)>>1),offt(a)+(offh(a)>>1)]},f=e(a),d=0;d<b.length;d++)b[d].dist=distance(e(b[d]),f);b.sort(function(a,b){return fZP(a.dist,b.dist)});b.length&&200>(c=b[0]).dist?this.paste(a,c):this.uG3(a)};this.o98=function(a,c){function b(b){b||
(b=window.event);var c=d(b),e=g(b);osl(a,i+(c-h));ost(a,k+(e-j));estp(b)}quiz.begin();c||(c=window.event);var e=document,f=q9("canvas"),d=this.Qb,g=this.Pk,h=d(c),j=g(c),i=h-(offw(a)>>1)-toffl(f),k=j-(offh(a)>>1)-tofft(f)-1,n=a.upHandler=function(c){c||(c=window.event);evd(e,"mousemove",b);evd(e,"mouseup",n);freehand.iE2(a)?freehand.Bf2(a):freehand.uG3(a);quiz.zH7||freehand.hjt();estp(c)};map(this.Mq,function(b){b.pasted==a&&(b.pasted=null)});aev(e,"mousemove",b);aev(e,"mouseup",n);f.appendChild(a);
b(c)}}
aWy([IS_FFOX?"#fZA *::-moz-selection, div.idq::-moz-selection, div.frhq::-moz-selection {background: transparent;}":"","div.freehand {text-align:left;position:absolute;font-family:'Lucida sans Unicode','Lucida Grande',sans-serif;font-weight:normal;border:1px solid #000;overflow:hidden;}","div.freehand *.fit {position:absolute;overflow:hidden;margin-left:1px;margin-top:1px;}",".idq {border:1px solid #000;color:#000 !important;cursor:pointer;font-family:'Lucida sans Unicode','Lucida Grande',sans-serif;font-weight:normal;white-space:nowrap;position:absolute;text-align:left;background:white;}","div.freehand .frhq {cursor:default;height:13px;width:13px;font-size:10px;text-align:center;vertical-align:middle;font-weight:bold;position:absolute;border:1px solid #000;overflow:hidden;-moz-box-sizing:border-box;box-sizing:border-box;background:white;}",
"#fZE {left:0px;top:0px;position:absolute;text-align:left;}","#fZA {position:relative;text-align:left;padding:5px;}",".idq p,.fit p {margin:0;}","input.fit {box-sizing:border-box}"]);if(document.onNewClass)document.onNewClass("Freehand");
