var jg_ihtm,jg_ie,jg_fast,jg_dom,jg_moz,jg_n4=document.layers&&"undefined"!=typeof document.classes;
function chkDHTM(b,e){jg_ie=(b=document.body||null)&&"undefined"!=typeof b.insertAdjacentHTML;jg_dom=b&&!jg_ie&&"undefined"!=typeof b.appendChild&&"undefined"!=typeof document.createRange&&"undefined"!=typeof(e=document.createRange()).setStartBefore&&"undefined"!=typeof e.createContextualFragment;jg_ihtm=!jg_ie&&!jg_dom&&b&&"undefined"!=typeof b.innerHTML;jg_fast=jg_ie&&document.all&&!window.opera&&J5&&8>J5;jg_moz=jg_dom&&"undefined"!=typeof b.style.MozOpacity}
function pntDoc(){this.wnd.document.write(jg_fast?this.Sf():this.htm);this.htm=""}function pntCnvDom(){var b=document.createRange();b.setStartBefore(this.cnv);b=b.createContextualFragment(jg_fast?this.Sf():this.htm);this.cnv.appendChild(b);this.htm=""}function pntCnvIe(){this.cnv.insertAdjacentHTML("BeforeEnd",jg_fast?this.Sf():this.htm);this.htm=""}function pntCnvIhtm(){this.cnv.innerHTML+=this.htm;this.htm=""}function pntCnv(){this.htm=""}
function mkDiv(b,e,a,d){this.htm+='<div style="position:absolute;left:'+b+"px;top:"+e+"px;width:"+a+"px;height:"+d+"px;clip:rect(0,"+a+"px,"+d+"px,0);background-color:"+this.color+(!jg_moz?";overflow:hidden":"")+(this.zIdx?";z-index:"+this.zIdx:"")+';"></div>'}function mkDivIe(b,e,a,d){this.htm+="%%"+this.color+";"+b+";"+e+";"+a+";"+d+";"}
function mkDivPrt(b,e,a,d){this.htm+='<div style="position:absolute;border-left:'+a+"px solid "+this.color+";left:"+b+"px;top:"+e+"px;width:"+a+"px;height:"+d+"px;clip:rect(0,"+a+"px,"+d+"px,0);background-color:"+this.color+(!jg_moz?";overflow:hidden":"")+(this.zIdx?";z-index:"+this.zIdx:"")+';"></div>'}function mkLyr(b,e,a,d){this.htm+='<layer left="'+b+'" top="'+e+'" width="'+a+'" height="'+d+'" bgcolor="'+this.color+'"></layer>\n'}var regex=/%%([^;]+);([^;]+);([^;]+);([^;]+);([^;]+);/g;
function Sf(){return this.htm.replace(regex,'<div style="overflow:hidden;position:absolute;background-color:$1;left:$2;top:$3;width:$4;height:$5"></div>\n')}function htmPrtRpc(){return this.htm.replace(regex,'<div style="overflow:hidden;position:absolute;background-color:transparent;left:$2;top:$3;width:$4;height:$5;border-left:$4px solid $1"></div>\n')}
function mkLin(b,e,a,d){if(b>a)var f=a,c=d,a=b,d=e,b=f,e=c;var f=a-b,c=Math.abs(d-e),g=e,l=e>d?-1:1;if(f>=c){for(var h=c<<1,j=h-(f<<1),i=h-f,e=b;0<f--;)++b,0<i?(this.mkDiv(e,g,b-e,1),g+=l,i+=j,e=b):i+=h;this.mkDiv(e,g,a-e+1,1)}else if(h=f<<1,j=h-(c<<1),i=h-c,f=g,d<=e){for(;0<c--;)0<i?(this.mkDiv(b++,g,1,f-g+1),g+=l,i+=j,f=g):(g+=l,i+=h);this.mkDiv(a,d,1,f-d+1)}else{for(;0<c--;)g+=l,0<i?(this.mkDiv(b++,f,1,g-f),i+=j,f=g):i+=h;this.mkDiv(a,f,1,d-f+1)}}
function mkLin2D(b,e,a,d){if(b>a)var f=a,c=d,a=b,d=e,b=f,e=c;var f=a-b,c=Math.abs(d-e),g=e,l=e>d?-1:1,h=this.stroke;if(f>=c){if(0<h-3)var j=(h*f*Math.sqrt(1+c*c/(f*f))-f-(h>>1)*c)/f,j=(!(h-4)?Math.ceil(j):mrnd(j))+1;else j=h;for(var h=Math.ceil(h/2),i=c<<1,k=i-(f<<1),m=i-f,e=b;0<f--;)++b,0<m?(this.mkDiv(e,g,b-e+h,j),g+=l,m+=k,e=b):m+=i;this.mkDiv(e,g,a-e+h+1,j)}else if(0<h-3?(j=(h*c*Math.sqrt(1+f*f/(c*c))-(h>>1)*f-c)/c,j=(!(h-4)?Math.ceil(j):mrnd(j))+1):j=h,h=mrnd(h/2),i=f<<1,k=i-(c<<1),m=i-c,f=g,
d<=e){for(++h;0<c--;)0<m?(this.mkDiv(b++,g,j,f-g+h),g+=l,m+=k,f=g):(g+=l,m+=i);this.mkDiv(a,d,j,f-d+h)}else{for(;0<c--;)g+=l,0<m?(this.mkDiv(b++,f,j,g-f+h),m+=k,f=g):m+=i;this.mkDiv(a,f,j,d-f+h+1)}}
function mkLinDott(b,e,a,d){if(b>a)var f=a,c=d,a=b,d=e,b=f,e=c;a-=b;f=Math.abs(d-e);c=e;e=e>d?-1:1;d=!0;if(a>=f)for(var g=f<<1,l=g-(a<<1),h=g-a;0<a--;)d&&this.mkDiv(b,c,1,1),d=!d,0<h?(c+=e,h+=l):h+=g,++b;else{g=a<<1;l=g-(f<<1);for(h=g-f;0<f--;)d&&this.mkDiv(b,c,1,1),d=!d,c+=e,0<h?(++b,h+=l):h+=g}d&&this.mkDiv(b,c,1,1)}
function mkOv(b,e,a,d){for(var f=a>>1,c=d>>1,a=a&1,d=(d&1)+1,b=b+f,e=e+c,g=0,l=c,h=0,j=c,i=f*f<<1,k=c*c<<1,m=(i>>1)*(1-(c<<1))+k,c=(k>>1)-i*((c<<1)-1),q,n;0<l;)0>m?(m+=k*((g<<1)+3),c+=(k<<1)*++g):0>c?(m+=k*((g<<1)+3)-(i<<1)*(l-1),c+=(k<<1)*++g-i*((l--<<1)-3),q=g-h,n=j-l,q&2&&n&2?(this.aV0(b,e,-g+2,h+a,-j,j-1+d,1,1),this.aV0(b,e,-g+1,g-1+a,-l-1,l+d,1,1)):this.aV0(b,e,-g+1,h+a,-j,j-n+d,q,n),h=g,j=l):(c-=i*((l<<1)-3),m-=(i<<1)*--l);this.mkDiv(b-f,e-j,f-h+1,(j<<1)+d);this.mkDiv(b+h+a,e-j,f-h+1,(j<<1)+
d)}
function mkOv2D(b,e,a,d){var f=this.stroke,a=a+(f-1),d=d+(f-1),c=a>>1,g=d>>1,l=a&1,h=(d&1)+1,b=b+c,e=e+g,j=0,i=g,k=c*c<<1,m=g*g<<1,q=(k>>1)*(1-(g<<1))+m,n=(m>>1)-k*((g<<1)-1);if(0>f-4&&(!(f-2)||0<a-51&&0<d-51)){for(var p=0,r;0<i;)0>q?(q+=m*((j<<1)+3),n+=(m<<1)*++j):0>n?(q+=m*((j<<1)+3)-(k<<1)*(i-1),n+=(m<<1)*++j-k*((i--<<1)-3),d=j-p,a=g-i,d-1?(r=d+1+(f&1),a=f):a-1?(r=f,a+=1+(f&1)):r=a=f,this.aV0(b,e,-j+1,p-r+d+l,-g,-a+g+h,r,a),p=j,g=i):(n-=k*((i<<1)-3),q-=(k<<1)*--i);this.mkDiv(b-c,e-g,f,(g<<1)+h);
this.mkDiv(b+c+l-f+1,e-g,f,(g<<1)+h)}else{a=a-(f-1<<1)>>1;p=d-(f-1<<1)>>1;r=0;var s=p,t=a*a<<1,u=p*p<<1,v=(t>>1)*(1-(p<<1))+u,w=(u>>1)-t*((p<<1)-1),f=[],d=[],a=[];f[0]=0;d[0]=g;for(a[0]=p-1;0<i;)0>q?(q+=m*((j<<1)+3),n+=(m<<1)*++j,f[f.length]=j,d[d.length]=i):0>n?(q+=m*((j<<1)+3)-(k<<1)*(i-1),n+=(m<<1)*++j-k*((i--<<1)-3),f[f.length]=j,d[d.length]=i):(n-=k*((i<<1)-3),q-=(k<<1)*--i),0<s&&(0>v?(v+=u*((r<<1)+3),w+=(u<<1)*++r,a[a.length]=s-1):0>w?(v+=u*((r<<1)+3)-(t<<1)*(s-1),w+=(u<<1)*++r-t*((s--<<1)-
3),a[a.length]=s-1):(w-=t*((s<<1)-3),v-=(t<<1)*--s,a[a.length-1]--));p=0;i=a[0];k=f.length;for(m=0;m<k;m++)if("undefined"!=typeof a[m]){if(a[m]<i||d[m]<g)j=f[m],this.aV0(b,e,-j+1,p+l,-g,i+h,j-p,g-i),p=j,g=d[m],i=a[m]}else j=f[m],this.mkDiv(b-j+1,e-g,1,(g<<1)+h),this.mkDiv(b+p+l,e-g,1,(g<<1)+h),p=j,g=d[m];this.mkDiv(b-c,e-g,1,(g<<1)+h);this.mkDiv(b+p+l,e-g,1,(g<<1)+h)}}
function mkOvDott(b,e,a,d){for(var f=a>>1,c=d>>1,a=a&1,d=d&1,b=b+f,e=e+c,g=0,l=c,f=f*f<<1,h=f<<1,j=c*c<<1,i=(f>>1)*(1-(c<<1))+j,c=(j>>1)-f*((c<<1)-1),k=!0;0<l;)0>i?(i+=j*((g<<1)+3),c+=(j<<1)*++g):0>c?(i+=j*((g<<1)+3)-h*(l-1),c+=(j<<1)*++g-f*((l--<<1)-3)):(c-=f*((l<<1)-3),i-=h*--l),k&&this.aV0(b,e,-g,g+a,-l,l+d,1,1),k=!k}function mkRect(b,e,a,d){var f=this.stroke;this.mkDiv(b,e,a,f);this.mkDiv(b+a,e,f,d);this.mkDiv(b,e+d,a+f,f);this.mkDiv(b,e+f,f,d-f)}
function mkRectDott(b,e,a,d){this.jf0(b,e,b+a,e);this.jf0(b+a,e,b+a,e+d);this.jf0(b,e+d,b+a,e+d);this.jf0(b,e,b,e+d)}function mkLinVirt(b,e,a,d,f){var c=Math.abs(d-e),f=Math.abs(f-a),a=e,d=e>d?-1:1,g,e=0;if(c>=f){var l=f<<1,h=l-(c<<1);for(g=l-c;0<c;)--c,0<g?(b[e++]=a,g+=h):g+=l,a+=d}else{l=c<<1;h=l-(f<<1);for(g=l-f;0<f;)--f,b[e++]=a,0<g?(a+=d,g+=h):g+=l}c=b.length;for(e=c-e;e;)b[c-e--]=a}
function wzMkArcDiv(b,e,a,d,f,c,g,l,h){var j=d+b+(c&65535),a=a-e,i,k;a||(a=1);b=d-b;h&16711680?(d=f-e-a,h&255?(h&2&&(i=Math.max(b,l[e]),k=j-i,0<k&&this.mkDiv(i,d,k,a)),h&1&&(k=Math.min(j,g[e]),k-=b,0<k&&this.mkDiv(b,d,k,a))):this.mkDiv(b,d,j-b,a),d=f+e+(c>>16),h&65280?(h&256&&(i=Math.max(b,g[e]),k=j-i,0<k&&this.mkDiv(i,d,k,a)),h&512&&(k=Math.min(j,l[e]),k-=b,0<k&&this.mkDiv(b,d,k,a))):this.mkDiv(b,d,j-b,a)):(h&255&&(i=h&2?Math.max(b,l[e]):b,k=h&1?Math.min(j,g[e]):j,k-=i,0<k&&this.mkDiv(i,f-e-a,k,
a)),h&65280&&(i=h&256?Math.max(b,g[e]):b,k=h&512?Math.min(j,l[e]):j,k-=i,0<k&&this.mkDiv(i,f+e+(c>>16),k,a)))}
function wzFillArc(b,e,a,d,f,c){var g=a>>1,l=d>>1,a=a&1|(d&1)<<16,b=b+g,e=e+l,d=0,h=l,j=d,i=h,k=g*g<<1,m=k<<1,q=l*l<<1,n=q<<1,p=(k>>1)*(1-(l<<1))+q,r=(q>>1)-k*((l<<1)-1),s=1<<(Math.floor((f%=360)/180)<<3)|2<<(Math.floor((c%=360)/180)<<3)|(f>=c)<<16,t=Array(l+1),u=Array(l+1),f=f*(Math.PI/180),c=c*(Math.PI/180),j=b+Math.round(g*Math.cos(f)),f=e+Math.round(-l*Math.sin(f));mkLinVirt(t,b,e,j,f);g=b+Math.round(g*Math.cos(c));c=e+Math.round(-l*Math.sin(c));for(mkLinVirt(u,b,e,g,c);0<h;)if(0>p)p+=q*((d<<
1)+3),r+=n*++d;else if(0>r)p+=q*((d<<1)+3)-m*(h-1),j=d,r+=n*++d-k*((h--<<1)-3),this.hZ8(j,h,i,b,e,a,t,u,s),i=h;else if(r-=k*((h<<1)-3),p-=m*--h,h&&(t[h]!=t[h-1]||u[h]!=u[h-1]))this.hZ8(d,h,i,b,e,a,t,u,s),i=h;this.hZ8(d,0,i,b,e,a,t,u,s);a>>16&&(s>>16?(c=f<=e||c>e?b-d:b,this.mkDiv(c,e,d+b-c+(a&65535),1)):s&1&&c>e&&this.mkDiv(b-d,e,d,1))}function jsgFont(){this.PLAIN="font-weight:normal;";this.BOLD="font-weight:bold;";this.ITALIC="font-style:italic;";this.vJ0=this.vq7=this.ITALIC+this.BOLD}
var Font=new jsgFont;function jsgStroke(){this.DOTTED=-1}var Stroke=new jsgStroke;
function wzGraphics(b,e){this.h95=new Function("arg","this.color = arg.toLowerCase();");this.jT2=function(a){this.stroke=a;a+1?(0<a-1?(this.jf0=mkLin2D,this.mkOv=mkOv2D):(this.jf0=mkLin,this.mkOv=mkOv),this.iY8=mkRect):(this.jf0=mkLinDott,this.mkOv=mkOvDott,this.iY8=mkRectDott);return!0};this.vZ1=function(a){this.printable=a;jg_fast?(this.mkDiv=mkDivIe,this.Sf=a?htmPrtRpc:Sf):this.mkDiv=jg_n4?mkLyr:a?mkDivPrt:mkDiv};this.Yh=function(a,d,f){this.G3=a||"Arial";this.q7=d;this.FX=f||Font.PLAIN};this.y56=
this.y57=function(a,d){for(var f=0;f<a.length-1;f++)this.jf0(a[f],d[f],a[f+1],d[f+1])};this.fillRect=function(a,d,f,c){this.mkDiv(a,d,f,c)};this.v56=function(a,d){a=map(a,mrnd);d=map(d,mrnd);this.y56(a,d);this.jf0(a[a.length-1],d[a.length-1],a[0],d[0])};this.v57=this.iY9=function(a,d,f,c){this.mkOv(a,d,f,c)};this.uZ4=this.iR9=function(a,d,f,c){var g=(f-=1)>>1,b=(c-=1)>>1,e=(f&1)+1,c=(c&1)+1,a=a+g,d=d+b,j=0,i=b,k=b,m=g*g<<1,q=m<<1,n=b*b<<1,p=(m>>1)*(1-(b<<1))+n,b=(n>>1)-m*((b<<1)-1),r,s,t;if(f+1)for(;0<
i;)0>p?(p+=n*((j<<1)+3),b+=(n<<1)*++j):0>b?(p+=n*((j<<1)+3)-q*(i-1),r=a-j,s=(j<<1)+e,b+=(n<<1)*++j-m*((i--<<1)-3),t=k-i,this.mkDiv(r,d-k,s,d+k-t+c+t-(d-k)),k=i):(b-=m*((i<<1)-3),p-=q*--i);this.mkDiv(a-g,d-k,f+1,(k<<1)+c)};this.hZ8=wzMkArcDiv;this.bJ9=wzFillArc;this.uZ3=function(a,d,f){var c,b,e,h,j,i,k,m,q,n=[],p=[],r=a.length;if(r){h=d[0];j=d[0];for(c=1;c<r;c++)d[c]<h&&(h=d[c]),d[c]>j&&(j=d[c]);for(e=h;e<=j;e++){var s=[];for(c=h=0;c<r;c++){c?(i=c-1,q=c):(i=r-1,q=0);b=d[i];m=d[q];if(b<m)i=a[i],k=
a[q];else if(b>m)m=d[i],b=d[q],k=a[i],i=a[q];else continue;e>=b&&e<m?s[h++]=mrnd((e-b)*(k-i)/(m-b)+i):e==j&&(e>b&&e<=m)&&(s[h++]=mrnd((e-b)*(k-i)/(m-b)+i))}s.sort(fZP);for(c=0;c<h;c+=2)b=s[c+1]-s[c]+1,f?e%4||n.push([s[c],e,b,4]):this.mkDiv(s[c],e,b,1)}if(n.length){n.sort(function(a,c){return fZP(a[0],c[0])||fZP(a[1],c[1])});for(c=n.length-2;0<=c;c--)n[c][0]==n[c+1][0]&&(n[c][1]+n[c][3]==n[c+1][1]&&n[c][2]==n[c+1][2])&&(n[c][3]+=n[c+1][3],n.splice(c+1,1));a="background:url("+cdns("/images/misc/fakesemitransp.gif")+
");position:absolute;font-size:0px;overflow:hidden;' ></div>";c=0;for(h=n.length;c<h;c++)p.push("<div style='left:",n[c][0],"px;top:",n[c][1],"px;width:",n[c][2],"px;height:",n[c][3],"px;",a);this.htm+=p.join("")}}};this.aZa=function(a,d){this.uZ3(a,d,!0)};this.fZF=function(){return"font-family:"+this.G3+";font-size:"+this.q7+";color:"+this.color+";"+this.FX+";"};this.u61=function(a,d,b){this.htm+='<div style="position:absolute;white-space:nowrap;left:'+d+"px;top:"+b+"px;"+this.fZF()+'">'+a+"</div>"};
this.fVL=function(a,d,b){this.u61('<div style="position:absolute;right:0;">'+a+"</div>",d,b)};this.txtlen=function(a){return a.toString().replace(/<[^>]+>/g,"").length};this.zH9=function(a,d,b){var d=mrnd(d),b=mrnd(b),d=d+1,c=this.txtlen(a);c&1&&c++;this.htm+='<div style="position:absolute;white-space:nowrap;width:0px;height:0px;overflow:visible;left:'+d+"px;top:"+b+"px;"+this.fZF()+'"><div style="position:absolute;left:-'+(c>>1)+"em;width:"+c+'em;text-align:center;">'+a+"</div></div>"};this.fZD=
function(a,d,b,c,e){a='<table style="position:absolute;overflow:visible;width:'+2*c+"px;height:"+2*e+"px;left:"+(d-c)+"px;top:"+(b-e)+'px;"><tr><td class="vam" style="text-align:center;width:'+2*c+"px;height:"+2*e+"px;"+this.fZF()+'">'+a+"</td></tr></table>";this.htm+=a};this.drawImage=function(a,b,f,c,e){this.htm+='<div style="position:absolute;left:'+b+"px;top:"+f+"px;width:"+c+";height:"+e+';"><img src="'+a+'" width="'+c+'" height="'+e+'"></div>'};this.clear=function(){this.htm="";this.cnv&&(this.cnv.innerHTML=
this.UW)};this.aV0=function(a,b,f,c,e,l,h,j){this.mkDiv(c+a,e+b,h,j);this.mkDiv(c+a,l+b,h,j);this.mkDiv(f+a,l+b,h,j);this.mkDiv(f+a,e+b,h,j)};this.jT2(1);this.Yh("verdana,geneva,helvetica,sans-serif",String.fromCharCode(49,50,112,120),Font.PLAIN);this.color="#000000";this.htm="";this.wnd=e||window;!jg_ie&&(!jg_dom&&!jg_ihtm)&&chkDHTM();"string"!=typeof b||!b?this.paint=pntDoc:(this.UW=(this.cnv=document.all?this.wnd.document.all[b]||null:document.getElementById?this.wnd.document.getElementById(b)||
null:null)&&this.cnv.innerHTML?this.cnv.innerHTML:"",this.paint=jg_dom?pntCnvDom:jg_ie?pntCnvIe:jg_ihtm?pntCnvIhtm:pntCnv);this.vZ1(J5);this.i9=this.iE=0;this.cnvW=this.cnv.offsetWidth;this.cnvH=this.cnv.offsetHeight;this.LINESTROKE=2;this.LINECOLOR="#6F7F7C";this.DARKEN="#4a5553";this.FILLCOLOR="#94A9A5";this.fZ4="#cad5d3";this.DARKCOLOR="#000000";this.CLEARCONTRAST="#4A55D3";this.COLORA="#6F7F7C";this.COLORB="#AFBFBC";this.LETTERH=20;this.LETTERW=10;this.LETTERSIZE=this.LETTERH+"px";this.LETTERSMALL=
mrnd(2*this.LETTERH/3)+"px";this.LETTERFONT="arial";this.LETTERSTYLE=0;this.TEXTPAD=5;this.jA4=function(a){this.htm+=a};this.jT6=function(){this.h95(this.LINECOLOR);this.Yh(this.LETTERFONT,this.LETTERSIZE,this.LETTERSTYLE);this.jT2(this.LINESTROKE)};this.jT7=function(){this.LETTERH=this.LETTERW=this.TEXTPAD=0};this.qE0=function(a){this.h95(this.DARKCOLOR);this.Yh(this.LETTERFONT,this.LETTERSMALL,this.LETTERSTYLE);this.u61(a,this.iE+this.TEXTPAD,this.i9+this.TEXTPAD);this.jT6()};this.uD4=function(a){this.u61(a,
(this.cnv.offsetWidth-a.length*this.LETTERW)/2,jA(150,this.cnv.offsetHeight/2))};this.jT6()}var jsGraphics=wzGraphics,Wz_jsg=1;if(document.onNewClass)document.onNewClass("jsGraphics");
